### ISSUE TITLE
How to set log path.

### ISSUE THREAD

**Issue by toomanycats** [cabeen/qit#2]
I'm using QIT on a grid engine. When something goes wrong with Java, I get a log in my home directory.
I'd like to set this log path to another location to keep all of them together.

I'm guessing `_JAVA_OPTIONS` would work, but I don't know which string to give it.

Thank you

**Comment by cabeen** [comment]
Hi Daniel,

If you are using the `qsubcmd` command, then you can specify the log directory with the `--qlog` flag.  But if you're using the grid engine another way, let me know, and I'll see if I can help.

Best,
Ryan

**Comment by toomanycats** [comment]
Hi Ryan.
I do set the stdout and stderr logs on our grid engine.
What I'm referring to is a Java log that ends up in my home directory.
Perhaps it's b/c I did some tests on a local host.

I'll get back to you if it keeps happening. 
Thank you
